GitHub-CI: Revert intentional differences on stable branch.
* .github/workflows/make-mingw.yaml, .github/workflows/make-ubnutu.yaml: Some
settings for the CI on GitHub are intentionally different between the stable and
the default branches. Revert some changes to the CI rules on the stable branch
after the default branch was merged to the stable branch.

diff --git a/.github/workflows/make-mingw.yaml b/.github/workflows/make-mingw.yaml
--- a/.github/workflows/make-mingw.yaml
+++ b/.github/workflows/make-mingw.yaml
@@ -21,7 +21,7 @@ jobs:
       matrix:
         # For available GitHub-hosted runners, see: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
         os: [windows-latest]
-        msystem: [MINGW64, CLANG64]
+        msystem: [MINGW64, UCRT64]
         include:
           - msystem: MINGW64
             mingw-prefix: mingw64
@@ -31,20 +31,14 @@ jobs:
             f77: gfortran
             extra-config-flags: ""
             ccache-max: 0.9G
-            allow-error: false
-          - msystem: CLANG64
-            mingw-prefix: clang64
-            target-prefix: mingw-w64-clang-x86_64
-            cc: clang
-            # It looks like we and graphicsmagick++ aren't ready for C++17 yet.
-            cxx: "clang++ -std=gnu++14"
-            f77: flang
-            # Clang seems to require a different set of dllexport attributes than GCC.
-            extra-config-flags:
-              --disable-lib-visibility-flags
-            ccache-max: 400M
-            # This configuration is not fully supported yet
-            allow-error: true
+          - msystem: UCRT64
+            mingw-prefix: ucrt64
+            target-prefix: mingw-w64-ucrt-x86_64
+            cc: gcc
+            cxx: g++
+            f77: gfortran
+            extra-config-flags: ""
+            ccache-max: 0.9G
 
     env:
       CHERE_INVOKING: 1
@@ -241,7 +235,6 @@ jobs:
           make -C ./.build DESTDIR=/c/octave/pkg install
 
       - name: test stand-alone executable
-        continue-on-error: ${{ matrix.allow-error }}
         run: |
           unset CC
           unset CXX
@@ -252,7 +245,6 @@ jobs:
           ./embedded.exe
 
       - name: test Octave packages
-        continue-on-error: ${{ matrix.allow-error }}
         env:
           # colon separated list of packages
           PACKAGE_NAMES: "control:stk"
@@ -278,22 +270,6 @@ jobs:
       - name: analyze test suite results
         # Make sure the test summary lists 0 "FAIL"s and no "REGRESSION"
         run: |
-          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || echo "::warning::At least one test failed"
-          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || echo "::warning::At least one regression in test suite"
+          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || (echo "::warning::At least one test failed" && exit 1)
+          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || (echo "::warning::At least one regression in test suite" && exit 1)
           echo Finished analyzing test suite results.
-
-      - name: compress build artifact
-        if: matrix.msystem == 'MINGW64'
-        continue-on-error: true
-        run: |
-          cd /c/octave/pkg
-          tar -cvzf octave.tar.gz *
-
-      - name: upload build artifact
-        if: matrix.msystem == 'MINGW64'
-        continue-on-error: true
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ matrix.target-prefix }}-octave-${{ steps.ccache-prepare.outputs.timestamp }}
-          path: C:\octave\pkg\octave.tar.gz
-          retention-days: 7
